# Generated by Django 2.1.5 on 2019-01-31 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('02b6e290-8d04-4b90-b409-24420ee817af'), editable=False, primary_key=True, serialize=False)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('F', 'FROM'), ('T', 'TO')], max_length=1)),
                ('client', models.UUIDField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.Bot'),
        ),
    ]
