# Generated by Django 2.1.5 on 2019-02-01 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7f647149-9374-4d5d-b742-1d7b6a144c6c'), editable=False, primary_key=True, serialize=False)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('F', 'FROM'), ('T', 'TO')], max_length=1)),
                ('client', models.UUIDField()),
                ('text', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.Bot')),
            ],
            options={
                'db_table': 'bots_messages',
            },
        ),
    ]
